// <auto-generated />
using System;
using CRUD.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD.Migrations
{
    [DbContext(typeof(CarvajaldbPrueba2Context))]
    [Migration("20200505133213_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD.Database.TipoIdentificacion", b =>
                {
                    b.Property<short>("CodTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("codTipoId")
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbreviTipoId")
                        .HasColumnType("nchar(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("NombreTipoId")
                        .HasColumnName("nombreTipoId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CodTipoId");

                    b.ToTable("TipoIdentificacion");
                });

            modelBuilder.Entity("CRUD.Database.Usuarios", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnName("id")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<short?>("TipoId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CRUD.Database.Usuarios", b =>
                {
                    b.HasOne("CRUD.Database.TipoIdentificacion", "Tipo")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoId")
                        .HasConstraintName("FK_Usuarios_TipoIdentificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
